### ISSUE TITLE
Can you please include the images of the ear also (if there are any)?

### ISSUE THREAD

**Issue by Tilakraj0308** [amini-allight/cipic-hrtf-database#1]

**Comment by amini-allight** [comment]
What I've uploaded here is all the original package contained. There are some images in the PDFs in the `doc` folder that might help with figuring out the data's orientation, including one drawing of an ear in `anthropometry.pdf`.

If other additional documentation files were available I'm not aware of them and I didn't manage to save them. You might have better luck contacting the University of California.

**Comment by Tilakraj0308** [comment]
Alright! thankyou for your response.
